
dataset_name: 'fb_amherst+fb_jh'
trans_dataset_name: 'pubmed'
out_dir: '../out/trans/amherst_jh_trans_pubmed'
seed: 42

num_pivots: 2000
hidden_size: 64
dropout: 0
feat_adj_dropout: 0.2
gl_dropout: 0
use_both_metric: True
graph_metric_type: 'weighted_cosine'
graph_skip_conn: 0.7
update_adj_ratio: 0.3
graph_learn_regularization: True
smoothness_ratio: 0
degree_ratio: 0
sparsity_ratio: 0.1
graph_learn_ratio: 0
graph_learn_hidden_size: 70
graph_learn_epsilon: 0
graph_learn_topk: null
graph_learn_num_pers: 4 
graph_hops: 2

optimizer: 'adam'
learning_rate: 0.01
weight_decay: 0.0005
grad_clipping: null
eary_stop_metric: 'nloss'
max_iter: 10
eps_adj: 8.5e-5 
max_episodes: 1

random_seed: 1234
max_epochs: 10000
patience: 100
print_every_epochs: 500

no_cuda: False
cuda_id: 0
